### ISSUE TITLE
Add new fields to listing form to make listings faster

### ISSUE THREAD

**Issue by EchterAgo** [acceptbitcoincash/acceptbitcoincash#1298]
I'd like to have 2 additional fields in the addition form which would probably make me much more efficient adding listings:

- "I am a company representative" checkbox. This should just be indicated in the created ticket. If this is checked it means we don't have to check their request as much.
- "Payment provider" optional text box. This should also just be included in the created ticket, not as keywords though. Or maybe we could make a selection of known big ones and people could just check the boxes?

**Comment by YusufKhan** [comment]
Could a "Discount for BCH payments" checkbox be added as well?
I think that's what vendors really need to show off to increase adoption.

**Comment by EchterAgo** [comment]
I agree with this, and I've seen people on reddit suggest it as well. Could
you create an issue for this? Don't bother filling the form, just write the
issue.

**Comment by EchterAgo** [comment]
Oh, sorry, I just saw you commented this on this issue. I think it's fine to mention it here without creating a new issue.

**Comment by EchterAgo** [comment]
I don't mean less verification on the legitimacy of the listing. I mean
less verification for things like what cryptocurrencies they accept. For
example with businesses where the site does not say anything about bitcoin,
I try to email them to ask if they do accept bitcoin. Also I often test the
checkout process. These could be omitted when the listing is submitted by
the owner.

**Comment by kenman345** [comment]
even then i dont trust it. Some folks think we wont list them if they accept BTC which is not true, but they usually leave it set to No anyways.

**Comment by EchterAgo** [comment]
Yea, you're right about that. Maybe a note on the page saying we don't
discriminate based on if a vendor accepts btc would help with that.

**Comment by kenman345** [comment]
Let me work on something. 

I think if we can get the form to indicate that all requests are manually processed and the better the information put into the form the quicker we can add them, that might help.

Additionally, we can add in a comment about caring to be accurate about all crypto accepted at a vendor so please fill out all questions about cryptocurrencies properly.

I'll reply with updated potential wordings when I get a chance.

I very much like the idea though of adding a github account name field. The biggest issue we have sometimes is requests that we have not enough information to contact anyone and actually add the listing. If we give the option to include the github account name then we can get in touch and they can see when the request has been added due to notifications.

**Comment by kenman345** [comment]
I have added a new field to our additions request form. It asks for a users github account name. This will be then mentioned in the opening of the issue and allow them to subsequently track the changes/request.

**Comment by kenman345** [comment]
I have updated the addition request form to have the following:
![Screenshot](https://i.imgur.com/1zmSUnQ.png)

Can easily revise though.

**Comment by kenman345** [comment]
this is an ongoing effort and will continue to be. I have made some optimizations to make things better, and also added changes in my PR #1329 to make it easier for github users to add listings by removing the alphabetical limitation by just setting the ordering ourselves with whatever is in the yml files we are about to use.
