### ISSUE TITLE
https://monovm.com & https://1gbits.com lisitng request

### ISSUE THREAD

**Issue by monovm** [acceptbitcoincash/acceptbitcoincash#1367]
https://monovm.com > hosting 
https://1gbits.com > datacenter

**Comment by kenman345** [comment]
Hi!

We dont have a datacenter section but if you submit our request form again for those with 'hosting' as the category, It should automatically create a Pull Request for the request now and we can easily merge it in.

https://acceptbitcoin.cash/add

otherwise,. please be patient as I work through this backlog we have.

**Comment by kenman345** [comment]
1gbits.com has been added, if you make a request with that form I mention above we can handle the request qquickly for you.
