### ISSUE TITLE
Include Call To Action in Social Buttons

### ISSUE THREAD

**Issue by maplesyrupsucker** [acceptbitcoincash/acceptbitcoincash#151]
I noticed if you compare https://acceptbitcoin.cash VS https://twofactorauth.org/ that the social buttons which share the pre-written message are completely different. TFA does a better job as the buttons encourage users to "tell them to support X on Twitter" 

Without that call to action it looks like you're just sharing company's twitter profiles versus messaging them on social media with a canned response. 

![image](https://user-images.githubusercontent.com/3764321/30998990-1a61c3ac-a50d-11e7-9219-c17bbf0bd1ac.png)

compared to: 

![image](https://user-images.githubusercontent.com/3764321/30998996-22366786-a50d-11e7-96af-785c16355a77.png)

**Comment by kenman345** [comment]
Thanks for the suggestion, We are taking this under consideration and working to identify the best way to implement this while maintaining proper view of the page.

Since sites may also already support BTC, it would mean the buttons are squeezed. Once we can implement a fix for this we will be able to add back in the Call to actions.

**Comment by kenman345** [comment]
@t0p0lin0 close this? or resolve this quickly?

**Comment by t0p0lin0** [comment]
Closing as this ("_Ask on..._") was added in the following commit: https://github.com/acceptbitcoincash/acceptbitcoincash/commit/f4656f283f5a7ed192979f5707fc71009fd8197b
