### ISSUE TITLE
Gaming: adding online go to the list

### ISSUE THREAD

**Issue by Uo124** [acceptbitcoincash/acceptbitcoincash#157]
https://online-go.com

**Comment by kenman345** [comment]
but you accept Bitcoin? Seems like a free site and an ads free option but no indication of taking any cryptocurrency for that functionality at all.

**Comment by Uo124** [comment]
Sorry I was not clear. Adding to the list of websites that currently do not accept bitcoin cash

**Comment by Uo124** [comment]
>  you accept payments at all. 

?

They accept donations...

**Comment by zquestz** [comment]
I logged in and checked the donations system, they only offer credit card and paypal. They don't even offer BTC. Not sure this should be included.

**Comment by kenman345** [comment]
We need to draw a line between realistic goals/worthwhile ventures and becoming a site that's free advertising. We will only list sites accepting donations if they are a large charity or they already accept Bitcoin Cash. We hope to bring the donation sites into its own page/section since they are different than the other types of sites we are trying to garner outreach for.

**Comment by Uo124** [comment]
They were even considering adding btc in past to their options. They were talking about that in the forum. (I don't know what happened). And there were a couple more people making pressure for them to accept. I think it was just because it seemed difficult to them, and they were busy with other stuff. 

But accepting here on a basis of being bigger or not, I think it might not be that good. The smaller websites usually are more receptive to new things, and have less bureaucracy, and could be more easily reachable, and accepting of change.  Plus it's simpler for them.
We just have to show them
