### ISSUE TITLE
GOURL.IO

### ISSUE THREAD

**Issue by cryptoapi** [acceptbitcoincash/acceptbitcoincash#182]
Gourl.io provide payment gateway for BCH https://gourl.io/bitcoincash-payment-gateway-api.html

**Comment by kenman345** [comment]
they're already in the code base we just havent deployed the latest changes yet. Hopefully will happen today. Closing this issue, thanks for your participation in this initiative and for trying to bring this to our attention. 

for reference: 
It was mentioned in #144 and then removed from the title so that the remaining items could be handled.

**Comment by kenman345** [comment]
Actually, scratch that. gourl is already listed on the live version of the site.
