### ISSUE TITLE
Summary of analytics

### ISSUE THREAD

**Issue by maplesyrupsucker** [acceptbitcoincash/acceptbitcoincash#1841]
Hey guys - wondering if any admins of acceptbitcoin.cash can reach out. 

The Bitcoin.com team is exploring the possibility of featuring some listings of online merchants accepting BCH using the websites API. But we wanted to know if anyone is able to share access to analytics so we can see which categories / services are most visited by shoppers.

Mainly looking for: 

1. Most popular categories
2. Most popular listings

Feel free to message me here or email me at corbin@bitcoin.com or dm me on telegram (corbinf) 

Thanks

Corbin

**Comment by kenman345** [comment]
hey, sorry i didnt get to you earlier. I do not believe we track in any considerable manner the pages one goes to since it all is loaded on the same page. we only can tell outside resolves to the ssite that open to a specific category. Otherwise we only have 3 main pages.

That said, we do have some JSON endpoints that have a pre-processed set of our data that can be used on any site that wants to.

these are https://acceptbitcoin.cash/data.json and https://acceptbitcoin.cash/stats.json

Let me know what else you were thinking about and if this helps.

**Comment by maplesyrupsucker** [comment]
Thanks @kenman345 - appreciate you taking the time to look into this. Are there any surprising stats from outside resolves to specific categories? 

We can likely just make our best guess and use the `stats.json` and assume count may impact total potential consumers looking for that service to be paid in bch. Thanks again

**Comment by kenman345** [comment]
honestly, its unwise to make any assumptions. Any changes on a weekly basis to that information (we only deploy changes to the site once a week if needed) will only be because we have vetted things. sometimes things sit for a while, other times something new is found thats been the case for months. I do hope to one day have instant additions made as we make changes but thats not in the cards right this moment.

**Comment by maplesyrupsucker** [comment]
That makes sense!

Any idea if event tracking on external clicks could be added someday? Would be great information to have.
