### ISSUE TITLE
How to address services that don't seem to have logos?

### ISSUE THREAD

**Issue by rawb0t** [acceptbitcoincash/acceptbitcoincash#190]
For example, cryptograffiti.info

No logo, not even a favicon. But its a cool BCC project that we should list. What about if we had a placeholder image that was just the standard BCC logo?

**Comment by kenman345** [comment]
well, @jrkong wrote an img organizing thing that would need changes and the base HTML that Jekyll uses would need changing if we were to define a base img. I would say we keep a 1 image per site match up, even if we use the same image for all, and rename appropriately. We can drop in in the future if they do get a logo."

as for the base image, I would say round BCC logo makes the most sense. We usually will see a lack of logo on startups and these newer sites are usually already supporting BCC when we add them.

**Comment by rawb0t** [comment]
That's what I'll do for now, then. If we come to a disagreement or a better solution I'll change it.

**Comment by t0p0lin0** [comment]
Sorry, reopening because I missed this, as you guys are too fast ;) Anyway, just wanted to chime in to say that I think a placeholder would be best, and I can try to account for that in the template logic, but as for the placeholder logo itself, I think it should be very generic, like a 'globe' icon to represent a website.

If you guys are cool with this, let's leave it open, and assign it to me so I can make those template changes. This way, the issues won't pile up if we don't have an image. 

Side point, if we get this 'fallback image' working, it would prolly be safe to remove the requirement on the `img` key in the YAML.

**Comment by rawb0t** [comment]
Yeah that's probably best -- but does it interfere with @jrkong's script? That may need to be edited to reflect this as well

**Comment by kenman345** [comment]
he will have to change it I think, but not too much. I thought my idea of having the img tag still contain a value and stuff was useful for the future when they do have a logo that we can swap it in without changing the yml. I'm good with whatever.

**Comment by t0p0lin0** [comment]
You're most likely correct, and I can talk with @jrkong -- though I am hoping it would only affect him/the script in a minor way.

**Comment by t0p0lin0** [comment]
@kenman345 -- sorry, we posted at the same time, didn't see your response. I do like the idea of still keeping the `img` key as required, but the caveat is that if it were to have a value of say `generic.png`, then that would be an additional thing to have to remember to set _exactly_. Thus, I recommend that we leave the `img` tag as *not* required, and if it is missing, we use `generic.png`.

**Comment by jrkong** [comment]
@t0p0lin0 I'll probably have to tweak the script a bit to account for these changes but it shouldn't be a problem. Though that said, how do you guys want the script to handle missing tags? Right now it just makes a note of all missing img tags and logs them but does nothing otherwise. 

Would you like the script to:
- Note entries missing the img tags and fill them in with generic.png after execution
or
- Note they exist and do nothing and assume someone will come along and fill it in/assume the site knows to default to generic.png

Assuming you want the former's behavior I could probably have the script route to a generic.png that's located in the root img directory because the script probably won't like the existence of a subdirectory that doesn't correspond with a yml file so it might purge it. I could code an exception for such cases but first I need to know how everyone wants everything handled.

**Comment by t0p0lin0** [comment]
Thanks @jrkong -- We were just discussing populating each `/img/{{category}}` folder with a copy of `generic.png`, so in this case, the former option may work, allowing the script to make life easier on us:

> Note entries missing the img tags and fill them in with generic.png after execution

Provided this works reliably, I think it may be best. In this case, you won't have to do anything extra, apart from just specifying `generic.png` in the missing entries `img` tag within the YAML.

Hope I am explaining my thoughts correctly, but let me know if not.

**Comment by jrkong** [comment]
Oh if that's the case it makes then it's even easier if each folder has its own generic.png and assuming the generic.png doesn't vary from folder to folder then the script should already clone a copy of generic.png into each directory assuming at least one instance of it is used. The code won't move generic.png into every directory right off the bat but it will copy/move generic.png as needed. 

So lets just say originally the site only had generic.png in Backup, Crypto and Banking but later on we add an entry that uses generic.png to Cloud the script will look through other directories for generic.png and copy it over to Cloud regardless in it's current implementation.

I was planning on doubling down on this by making the code make sure a copy of generic.png exists once it adds generic.png to an entry in the yml file. Of course this won't ensure generic.png will be in each and every directory right off the bat but if you want that to happen I can get it to work.

As for automatically filling in missing tags, it shouldn't be too hard, I can get the code to rebuild the file as it runs and write the entire thing after it's read through the yml file.

**Comment by t0p0lin0** [comment]
That's a stellar plan really. Nice! Let's just test it carefully, as the script would be modifying the YAMLs, so we just want to ensure it's rock solid. Love your suggestion though.

**Comment by kenman345** [comment]
make sure it doesnt mess up file encoding or spacing...pls and thx u

**Comment by jrkong** [comment]
Yup I remember the problems we've had cuz of those. Encoding won't be a problem for sure because every file operation the scripts does defaults to utf-8, the spacing, however, I'm will cause some problems on my first few attempts.

**Comment by kenman345** [comment]
Dont we have it defaulting to a generic image now? Can we close out this issue to help clean things up?

**Comment by t0p0lin0** [comment]
It doesn't default to a generic image, but what we were doing was copying `generic.png` into the `img/{{category}}` folder (if it wasn't already there), and assigning that image to the vendor, which is the old school "missing image" graphic from old browsers.

We can still close this issue, because if an image is not provided, there should be a blank gray background in its place. May wish to test before we do close it, but yes, this issue can be cleaned up.

**Comment by kenman345** [comment]
Cant we look for the img tag being generic.png and just use the root instead of subpath then?

**Comment by t0p0lin0** [comment]
Can probably try to put some conditional logic within the Jekyll template...just not sure when.

**Comment by kenman345** [comment]
we added in the generic logo so this is getting closed
