### ISSUE TITLE
Why do we have the /notes folder?

### ISSUE THREAD

**Issue by kenman345** [acceptbitcoincash/acceptbitcoincash#477]
2FA used it for this: 
https://github.com/2factorauth/twofactorauth/blob/master/_data/banking.yml#L189

https://twofactorauth.org/notes/chase/

but we dont do any of that. Shall we just remove those entirely to avoid bloat?

**Comment by kenman345** [comment]
Or do we perhaps make use of those as partials for the charity section we were considering?

**Comment by t0p0lin0** [comment]
Please leave it for now, as I was using it as reference for the other pages, however by now I have a good grasp. I will remove it around the same time I do the refactoring for other page support. Assigning to myself.

**Comment by kenman345** [comment]
btw:   
*  image /img/placeholder.png does not have an alt attribute (line 9154)
*  image /img/placeholder.png does not have an alt attribute (line 17584)

**Comment by t0p0lin0** [comment]
At the same time, clean up the plethora of validation errors @ https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Facceptbitcoin.cash

**Comment by t0p0lin0** [comment]
I'll try to remember to take care of the remaining ...

• [ ] Evaluate some 'Other' section items to see if we can separate them into already defined sections. A lot of them are just carry-overs from the 2factorauth site we forked at the beginning of the project and we've added new sections since then and havent gone to the 'Other' section to re-evaluate things

...task during the refactoring of page template code/includes.

**Comment by kenman345** [comment]
yes please and thank you
