### ISSUE TITLE
Add a Newsletter/Magazine type of category

### ISSUE THREAD

**Issue by hegjon** [acceptbitcoincash/acceptbitcoincash#507]
I am not sure what category to put:
- Counter Markets - http://countermarkets.com/
- The Dollar Vigilante - https://dollarvigilante.com/

Both are newsletters that sends out PDF to subscribers.

**Comment by kenman345** [comment]
We added a few categories recently and we decided as a whole that the adding of new categories needs to be due to a multitude of merchants that would be able to be moved to it immediately, or multiple merchants added. 

If you can identify legitimate candidates for accepting BCH and even a few that do, then we would indeed be able to accomodate a new category for these. In the meantime, I think these best belong to the Entertainment section.

**Comment by kenman345** [comment]
Just keeping this issue alive. Not opposed to adding a new section as we just added "services" in a PR thats currently pending. Maybe we throw these into that until we feel they might do better being with others in a news category?

**Comment by hegjon** [comment]
I think services is a good category to move them to

**Comment by kenman345** [comment]
I’ll add them to the open PR then if I find the time today

**Comment by hegjon** [comment]
Books could also be included in this category

**Comment by kenman345** [comment]
these are already added, so closing
